In [3]:
from scipy.special import comb, perm

import numpy as np

comb(10,5)/np.power(2,10)  

0.24609375

In [6]:
comb(10,9)*np.power(0.9,9)*0.1

0.38742048900000015

In [7]:
comb(10,9)*np.power(0.1,9)*0.9+np.power(0.1,10)

9.100000000000004e-09

In [9]:
2*np.exp(-2*10*0.8*0.8)

5.521545144074397e-06

In [10]:
(4+4*30)/1024

0.12109375

In [21]:
import pandas as pd
df=pd.read_csv('/Users/idealab/Desktop/资产定价/爬虫与机器学习/机器学习/林轩田作业1/hw1_15_train.dat',sep='\s+',header=None,names=["UserID","Gender","Age","Occupation","Zipcode"])

In [46]:
df.insert(0,'constant', 1, allow_duplicates=False)

In [47]:
df

constant    UserID    Gender       Age  Occupation  Zipcode
0           1  0.976810  0.107230  0.643850    0.295560        1
1           1  0.671940  0.241800  0.830750    0.427410        1
2           1  0.206190  0.233210  0.810040    0.986910        1
3           1  0.515830  0.055814  0.922740    0.757970        1
4           1  0.708930  0.108360  0.339510    0.770580        1
..        ...       ...       ...       ...         ...      ...
395         1  0.712060  0.515690  0.181680    0.555700        1
396         1  0.175280  0.262500  0.830600    0.029669       -1
397         1  0.938950  0.939410  0.724960    0.956550        1
398         1  0.046136  0.944130  0.038311    0.268120       -1
399         1  0.072491  0.224200  0.625920    0.672380        1

[400 rows x 6 columns]

In [48]:
x=np.matrix(df.iloc[:,:5])
y=np.matrix(df.iloc[:,-1:])

In [49]:
x

matrix([[1.      , 0.97681 , 0.10723 , 0.64385 , 0.29556 ],
        [1.      , 0.67194 , 0.2418  , 0.83075 , 0.42741 ],
        [1.      , 0.20619 , 0.23321 , 0.81004 , 0.98691 ],
        ...,
        [1.      , 0.93895 , 0.93941 , 0.72496 , 0.95655 ],
        [1.      , 0.046136, 0.94413 , 0.038311, 0.26812 ],
        [1.      , 0.072491, 0.2242  , 0.62592 , 0.67238 ]])

In [50]:
y

matrix([[ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [-1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [ 1],
      

In [51]:
w=np.matrix([[0,0,0,0,0]])

In [86]:
def sign(x):
    if x>0:
        return 1
    else:
        return -1

In [130]:
def pla(x,y,w,i,num):
    if num==len(x):
        return 0
    else:
        if sign((x*w.T)[i,0])*y[i,0]<0:
            return 1+pla(x,y,w+y[i,0]*x[i],(i+1)%len(x),0)
        return pla(x,y,w,(i+1)%len(x),num+1)

In [128]:
pla(x,y,w,0,0)

[[-3.         3.0841436 -1.583081   2.391305   4.5287635]]


45

In [132]:
s=0
for i in range(2000):
    arr=np.append(x,y,axis=1)
    np.random.shuffle(arr)
    s=s+pla(np.matrix(arr[:,:-1]),np.matrix(arr[:,-1:]),w,0,0)
s/2000

40.2855

In [133]:
def pla(x,y,w,i,num):
    if num==len(x):
        return 0
    else:
        if sign((x*w.T)[i,0])*y[i,0]<0:
            return 1+pla(x,y,w+0.5*y[i,0]*x[i],(i+1)%len(x),0)
        return pla(x,y,w,(i+1)%len(x),num+1)

In [125]:
pla(x,y,w,0,0)

45

In [134]:
s=0
for i in range(2000):
    arr=np.append(x,y,axis=1)
    np.random.shuffle(arr)
    s=s+pla(np.matrix(arr[:,:-1]),np.matrix(arr[:,-1:]),w,0,0)
s/2000

40.032

## 18-20

In [5]:
import pandas as pd
import numpy as np
df=pd.read_csv('/Users/idealab/Desktop/资产定价/爬虫与机器学习/机器学习/林轩田作业1/hw1_18_train.dat',sep='\s+',header=None,names=["UserID","Gender","Age","Occupation","Zipcode"])
df.insert(0,'constant', 1, allow_duplicates=False)

def sign(x):
    if x>0:
        return 1
    else:
        return -1
x=np.matrix(df.iloc[:,:5])
y=np.matrix(df.iloc[:,-1:])
j=0
w=np.matrix([[0,0,0,0,0]])
for i in range(50):
    num=0
    while(sign((x*w.T)[j,0])*y[j,0]>0 and num<=len(x)):
        j=(j+1)%len(x)
        num=num+1
    if num<=len(x):
        w=w+y[j,0]*x[j]
    j=(j+1)%len(x)
w

df1=pd.read_csv('/Users/idealab/Desktop/资产定价/爬虫与机器学习/机器学习/林轩田作业1/hw1_18_test.dat',sep='\s+',header=None,names=["UserID","Gender","Age","Occupation","Zipcode"])
df1.insert(0,'constant', 1, allow_duplicates=False)
df1
x=np.matrix(df1.iloc[:,:5])
y=np.matrix(df1.iloc[:,-1:])
s=0
for i in range(len(x)):
    if sign((x*w.T)[i,0])!=y[i,0]:
        s=s+1
s/len(x)

0.292

## pla

In [6]:
s=0
for i in range(2000):
    x=np.matrix(df.iloc[:,:5])
    y=np.matrix(df.iloc[:,-1:])
    arr=np.append(x,y,axis=1)
    np.random.shuffle(arr)
    a=np.matrix(arr[:,:-1])
    b=np.matrix(arr[:,-1:])
    w=np.matrix([[0,0,0,0,0]])
    j=0
    for i in range(50):
        num=0
        while(sign((a*w.T)[j,0])*b[j,0]>0 and num<=len(a)):
            j=(j+1)%len(a)
            num=num+1
        if num<=len(a):
            w=w+b[j,0]*a[j]
        j=(j+1)%len(a)
    x=np.matrix(df1.iloc[:,:5])
    y=np.matrix(df1.iloc[:,-1:])
    for j in range(len(x)):
        if sign((x*w.T)[j,0])!=y[j,0]:
            s=s+1
s/(2000*len(x))

0.359081

## pocket

In [361]:
x[1,:]

matrix([[1.      , 0.32368 , 0.61439 , 0.42097 , 0.025626]])

In [382]:
import copy as cp
df=pd.read_csv('/Users/idealab/Desktop/资产定价/爬虫与机器学习/机器学习/林轩田作业1/hw1_18_train.dat',sep='\s+',header=None,names=["UserID","Gender","Age","Occupation","Zipcode"])
df.insert(0,'constant', 1, allow_duplicates=False)
df1=pd.read_csv('/Users/idealab/Desktop/资产定价/爬虫与机器学习/机器学习/林轩田作业1/hw1_18_test.dat',sep='\s+',header=None,names=["UserID","Gender","Age","Occupation","Zipcode"])
df1.insert(0,'constant', 1, allow_duplicates=False)


size=0
for m in range(100):
    x=np.matrix(df.iloc[:,:5])
    y=np.matrix(df.iloc[:,-1:])
    arr=np.append(x,y,axis=1)
    np.random.shuffle(arr)
    a=np.matrix(arr[:,:-1])
    b=np.matrix(arr[:,-1:])
    w=np.matrix([[0,0,0,0,0]])
    count=0
    err=1
    for j in range(len(a)):
        if (a[j,:]*(w.T))*b[j,0]<=0:
            count+=1
            w=w+b[j,0]*a[j,:]
            s=0
            for i in range(len(x)):
                if (a[i,:]*(w.T))*b[i,0]<=0:
                    s=s+1
            err1=s/len(a)
            if err1<err:
                w1=cp.deepcopy(w)
                err=err1

        if count==100:
            break
    x=np.matrix(df1.iloc[:,:5])
    y=np.matrix(df1.iloc[:,-1:])
    for k in range(len(x)):
        if (x*(w1.T))[k,0]*y[k,0]<=0:
            size=size+1
size/(100*len(x))

0.11462

In [335]:
type(y[0,0])

numpy.int64

In [221]:
s=0
for m in range(2000):
    x=np.matrix(df.iloc[:,:5])
    y=np.matrix(df.iloc[:,-1:])
    arr=np.append(x,y,axis=1)
    np.random.shuffle(arr)
    a=np.matrix(arr[:,:-1])
    b=np.matrix(arr[:,-1:])
    w=np.matrix([[0.1,0,0,0,0]])
    for k in range(100):
        num=0
        while(sign((a*w.T)[j,0])*b[j,0]>0 and num<=len(a)):
            j=(j+1)%len(a)
            num=num+1
        if num<=len(a):
            w1=w+b[j,0]*a[j]
            s=0
            for i in range(len(x)):
                if (x*w.T)[i,0]*y[i,0]<=0:
                    s=s+1
            err=s/len(x)
            s=0
            for i in range(len(x)):
                if (x*w1.T)[i,0]*y[i,0]<=0:
                    s=s+1
            err1=s/len(x)            
            if err1<err:
                w=w1
        j=(j+1)%len(a)
    x=np.matrix(df1.iloc[:,:5])
    y=np.matrix(df1.iloc[:,-1:])
    for j in range(len(x)):
        if sign((x*w.T)[j,0])!=y[j,0]:
            s=s+1
s/(2000*len(x))

KeyboardInterrupt: 

In [207]:
df

constant    UserID    Gender       Age  Occupation  Zipcode
0           1  0.945440  0.428420  0.798330    0.162440       -1
1           1  0.853650  0.084168  0.568200    0.492210       -1
2           1  0.170950  0.821270  0.984440    0.514860       -1
3           1  0.514120  0.921240  0.423230    0.097934       -1
4           1  0.281470  0.714340  0.075309    0.911600        1
..        ...       ...       ...       ...         ...      ...
495         1  0.542960  0.959950  0.384460    0.111450       -1
496         1  0.374380  0.128740  0.752800    0.977680        1
497         1  0.078827  0.382300  0.139650    0.826770        1
498         1  0.922880  0.863130  0.229390    0.922140       -1
499         1  0.503150  0.418840  0.026094    0.916230        1

[500 rows x 6 columns]

In [225]:
y.sum()

-202

In [226]:
y

matrix([[ 1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [ 1],
        [-1],
        [ 1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [-1],
        [ 1],
        [-1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [ 1],
        [ 1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
        [-1],
      

In [381]:
import pandas as pd
import numpy as np
import copy as cp
 
 
def get_training_set():
    # 读取.dat文件，并用\s+匹配空格读取出五列数据，header将第一行放入数据（否则第一行是列名）
    data = pd.read_csv('/Users/idealab/Desktop/资产定价/爬虫与机器学习/机器学习/林轩田作业1/hw1_18_train.dat', sep='\s+', names=['a', 'b', 'c', 'd', 'y'])
    # 构建特征向量X
    X_train = np.array(data.iloc[:, 0:4])
    # 训练集大小
    data_size = X_train.shape[0]
    # 训练集X加上一列1
    X_train = np.hstack((np.ones((data_size, 1)), X_train))
    # 构建标签y
    y_train = np.array(data.iloc[:, 4:5])
    # 打乱数据
    list = np.random.permutation(data_size)
    X_train = X_train[list]
    y_train = y_train[list]
 
    return X_train, y_train, data_size
 
 
def get_test_set():
    data = pd.read_csv('/Users/idealab/Desktop/资产定价/爬虫与机器学习/机器学习/林轩田作业1/hw1_18_test.dat', sep='\s+', names=['a', 'b', 'c', 'd', 'y'])
    # 初始化测试集
    test_set = np.array(data)
    # 测试集大小
    test_size = test_set.shape[0]
    # 测试X与y分组
    X_val = test_set[:, 0:4]
    X_val = np.hstack((np.ones((test_size, 1)), X_val))
    y_val = test_set[:, 4:5]
 
    return X_val, y_val, test_size
 
 
def Pocket():
    X_train, y_train, data_size = get_training_set()
    # 初始化w
    w = np.zeros((5, 1))
    count = 0
    max_iters = data_size
    w_pocket = np.zeros((5, 1))
 
    for i in range(data_size):
        if np.dot(X_train[i, :], w) * y_train[i, :] <= 0:
            w +=   y_train[i, :] * X_train[i, :].reshape(5, 1)
            #计数器加一
            count += 1
            validation = 0
            #验证w，是否放入口袋
            for j in range(data_size):
                if np.dot(X_train[j, :], w) * y_train[j, :] <= 0:
                    validation += 1
            if validation < max_iters:
                #验证次数，如果比上一次小，就将新的w放入pocket
                max_iters = validation
                w_pocket = cp.deepcopy(w)
            #迭代次数达到50次时，退出循环
            if 50 == count:
                break
 
    return w_pocket
 
 
def Pocket_Error(w_pocket):
    X_val, y_val, test_size = get_test_set()
    error_num = 0
    # 验证错误个数
    for i in range(test_size):
        if np.dot(X_val[i, :], w_pocket) * y_val[i, :] <= 0:
            error_num += 1
    error_ratio = error_num/test_size
 
    return error_ratio
 
 
if __name__ == '__main__':
    ratio_sum = 0
    for i in range(100):
        w_pocket = Pocket()
        ratio = Pocket_Error(w_pocket)
        ratio_sum += ratio
    ave_ratio = ratio_sum/100
    print(ave_ratio)


0.12509999999999993


In [359]:
if np.matrix([[False]]):
    print(1)